name = "akimatch"
main = ".open-next/worker.js"
compatibility_date = "2026-05-08"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "akimatch_db"
database_id = "b576f5fb-9214-4392-bf3b-c40f4e9f638c"
migrations_dir = "drizzle"
